# Generated by Django 4.1 on 2022-09-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_familiares_lista_delete_familiares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('parentesco', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('year_born', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='familiares_lista',
        ),
    ]
