# Generated by Django 4.1 on 2022-08-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('year_born', models.DateField()),
            ],
        ),
    ]
